### ISSUE TITLE
Login broken by Google ?

### ISSUE THREAD

**Issue by tym-project** [Tatsh/youtube-unofficial#1]
the login function fails on "galx = re.search(r'(?s)<input.+?name="GALX".+?value="(.+?)"',                       login_page).group(1)" :
```
Traceback (most recent call last):
  File "./<edited path>.py", line 210, in <module>
    yt.login()
  File "/<edited path>/youtube_unofficial/__init__.py", line 160, in login
    login_page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```
If I manually look at the source code for the login page, I can't find any "GALX" attribute anywhere.

**Comment by Tatsh** [comment]
Will look into this. My cookies generated by the current code have been working for a very long time.

**Comment by Tatsh** [comment]
Since this code is based on youtube-dl it's possible they have updated their code or their login is broken.

**Comment by tym-project** [comment]
OK, is there anything I can do to help maybe ?

**Comment by Tatsh** [comment]
The login code has changed considerably. If you can port the current code over and make it work that would be helpful. Since I store cookies in my login() method and have a TFA callback argument, I cannot really call their code directly.

https://github.com/rg3/youtube-dl/blob/ddbb4c5c3ea7a64e09834d9628e7e34e03675289/youtube_dl/extractor/youtube.py#L78

**Comment by Tatsh** [comment]
I have fixed this. Committing now.

**Comment by tym-project** [comment]
Thank you, I'll take a look as soon as I can.
