### ISSUE TITLE
Hello, the new version seems to have a problem.

### ISSUE THREAD

**Issue by Aruelius** [Tatsh/youtube-unofficial#5]
Looking at the error message seems to be a problem when the prepped is passed to the session.

![image](https://user-images.githubusercontent.com/25380989/58757254-b2bff500-853b-11e9-824b-cf4dbb5f62ad.png)

**Comment by Tatsh** [comment]
I am not getting this issue. I see in your output you have ^C which means you had to have hit Ctrl+C or similar. There is no output from a call to `login()`.

```pycon
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(ins)>>> from youtube_unofficial import YouTube
(ins)>>> x = YouTube()
(ins)>>> x.login()
(ins)>>> x._logged_in
True
```

**Comment by MikuShare** [comment]
Thank you for your reply.
I pressed Ctrl+C because if I didn't stop it at the time, It wouldn't give any feedback.
Now it prompts for the wrong password: youtube_unofficial.exceptions.AuthenticationError: Incorrect password
![image](https://user-images.githubusercontent.com/25380989/58757849-e738ae80-8545-11e9-8215-1fa03babbede.png)

But my password is correct.

I have five servers, but it can only log in on one of the servers. The rest of the servers will prompt Incorrect password

**Comment by Tatsh** [comment]
>I have five servers, but it can only log in on one of the servers. The rest of the servers will prompt Incorrect password

I think Google may be flagging the IPs of some of these servers.

**Comment by MikuShare** [comment]
But when I use the IP of another server as a proxy, login is no problem.

**Comment by Aruelius** [comment]
Hello, I think the login method has completely failed. I can log in because I remember this server and you can test it for another server.

**Comment by Aruelius** [comment]
This is youtube-dl's code:
![image](https://user-images.githubusercontent.com/25380989/60009890-3dae8e00-96a9-11e9-86a9-b87f1e36d9f3.png)
1 is a int
